name: The Cyborg Cirus Project (name field)
title: The Cyborg Circus Project (title field)
description: Website for the Cyborg Circus Project (description field)

theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
