name: The Cyborg Cirus Project
title: The Cyborg Circus Project
description: Some kind of catchy phrase goes here. Jen, Shay, say something clever.

theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
